select * from PLAYER
select * from TEAM
select * from STADIUM
--1. Display players who belong to teams located in ‘Mumbai’.
SELECT * FROM PLAYER
INNER JOIN TEAM
ON PLAYER.TEAM_ID=TEAM.TEAM_ID
INNER JOIN STADIUM
ON TEAM.HOME_STADIUM_ID=STADIUM.STADIUM_ID
WHERE STADIUM_CITY='MUMBAI'

--2. Display all teams and players.
SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID

--3. Display players along with team wins and stadium city.
SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME,TEAM_NAME,TEAM_WINS,STADIUM_CITY FROM PLAYER
INNER JOIN TEAM
ON PLAYER.TEAM_ID=TEAM.TEAM_ID
INNER JOIN STADIUM
ON TEAM.HOME_STADIUM_ID=STADIUM.STADIUM_ID

--4. Display team name and number of players in each team.
SELECT COUNT(PLAYER_ID) AS NO_OF_PLAYERS,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--5. Display team name, coach, and number of bowlers in each team.
SELECT COUNT(PLAYER_ROLE) AS NO_OF_PLAYERSBOWLERS,TEAM_NAME,TEAM_COACH FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
WHERE PLAYER_ROLE='BOWLER'
GROUP BY TEAM_NAME,TEAM_COACH

--6. Display team name with count of batsmen, bowlers, and all-rounders.
SELECT COUNT(PLAYER_ROLE) AS NO_OF_PLAYERS,PLAYER_ROLE,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
WHERE PLAYER_ROLE!='WICKETKEEPER'
GROUP BY PLAYER_ROLE,TEAM_NAME

--7. Display stadiums where teams have won more than 10 matches.
SELECT STADIUM_NAME,TEAM_WINS FROM TEAM 
INNER JOIN STADIUM
ON TEAM.HOME_STADIUM_ID=STADIUM.STADIUM_ID
WHERE TEAM_WINS>10
GROUP BY TEAM_WINS,STADIUM_NAME

--8. Display team name and number of players whose matches played is greater than 25.
SELECT COUNT(PLAYER_MATCHES_PLAYED) AS NO_OF_PLAYERS,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
WHERE PLAYER_MATCHES_PLAYED>25
GROUP BY TEAM_NAME

--9. Display team name and total number of players having jersey number greater than 30.
SELECT COUNT(*) AS NO_OF_PLAYERS,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
WHERE PLAYER_JERSEY_NUMBER>30
GROUP BY TEAM_NAME

--10. Display team name and total matches played by its players. 
SELECT SUM(PLAYER_MATCHES_PLAYED) AS TOTAL_MATCHES_PALYED,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--11. Display stadium city and total number of teams in each city.
SELECT COUNT(*) AS TOTAL_TEAMS,STADIUM_CITY FROM STADIUM
INNER JOIN TEAM
ON TEAM.HOME_STADIUM_ID=STADIUM.STADIUM_ID
GROUP BY STADIUM_CITY

--12. Display team name and average matches played by players in each team.
SELECT AVG(PLAYER_MATCHES_PLAYED) AS AVG_MATCHES_PALYED,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--13. Display team name and maximum matches played by any player in each team.
SELECT MAX(PLAYER_MATCHES_PLAYED) AS MAX_MATCHES_PALYED,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--14. Display team name and minimum matches played by any player in each team.
SELECT MIN(PLAYER_MATCHES_PLAYED) AS MIN_MATCHES_PALYED,TEAM_NAME FROM PLAYER
INNER JOIN TEAM
ON TEAM.TEAM_ID=PLAYER.TEAM_ID
GROUP BY TEAM_NAME

--15. Display stadium name and total number of players playing under teams of that stadium.
SELECT SUM(PLAYER_ID) AS NO_OF_PLAYERS,STADIUM_NAME FROM PLAYER
INNER JOIN TEAM
ON PLAYER.TEAM_ID=TEAM.TEAM_ID
INNER JOIN STADIUM
ON TEAM.HOME_STADIUM_ID=STADIUM.STADIUM_ID
GROUP BY STADIUM_NAME

-- 16. Display teams having more all-rounders than bowlers.
SELECT TEAM_NAME
FROM TEAM 
INNER JOIN PLAYER ON TEAM.TEAM_ID = PLAYER.TEAM_ID 
GROUP BY TEAM.TEAM_NAME 
HAVING COUNT(CASE WHEN PLAYER.PLAYER_ROLE = 'All-rounder' THEN 1 END) > COUNT(CASE WHEN PLAYER.PLAYER_ROLE = 'Bowler' THEN 1 END);

-- 17. Display teams where difference between max and min player matches is greater than 5.
SELECT TEAM_NAME 
FROM TEAM 
JOIN PLAYER ON TEAM.TEAM_ID = PLAYER.TEAM_ID 
GROUP BY TEAM_NAME 
HAVING (MAX(PLAYER.PLAYER_MATCHES_PLAYED) - MIN(PLAYER.PLAYER_MATCHES_PLAYED)) > 5;

-- 18. Display stadium city and total wins of teams in that city.
SELECT STADIUM_CITY, SUM(TEAM_WINS) AS TOTAL_WINS 
FROM STADIUM 
JOIN TEAM ON STADIUM.STADIUM_ID = TEAM.HOME_STADIUM_ID 
GROUP BY STADIUM.STADIUM_CITY;

-- 19. Display team name and total number of players for each role (grouped by role).
SELECT TEAM_NAME, PLAYER_ROLE, COUNT(PLAYER_ID) AS TOTAL_PLAYERS 
FROM TEAM 
JOIN PLAYER ON TEAM.TEAM_ID = PLAYER.TEAM_ID 
GROUP BY TEAM_NAME, PLAYER_ROLE;

-- 20. Display team name and total number of players whose name starts with 'A'
SELECT TEAM_NAME, COUNT(PLAYER_ID) AS PLAYER_COUNT 
FROM TEAM 
JOIN PLAYER ON TEAM.TEAM_ID = PLAYER.TEAM_ID 
WHERE PLAYER_FIRST_NAME LIKE 'A%' 
GROUP BY TEAM_NAME;